name: idream
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# this application is run on the flutter version 2.0.2 so don't change the version don't be smart
version: 1.3.0+130

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  image_picker: ^0.8.4+4
#  image_cropper: ^3.0.1
  image_cropper: ^1.4.1
  video_player: ^2.4.7
  google_fonts: ^3.0.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  firebase_database: ^10.0.3
  pin_input_text_field: ^4.1.1
  otp_autofill: ^2.1.0
  shared_preferences: ^2.0.12
  google_sign_in: ^5.4.2
  http: ^0.13.4
  sign_in_with_apple: ^4.1.0
  the_apple_sign_in: ^1.1.1
#  crypto: ^3.0.1
  random_string: ^2.3.1
  sqflite: any
  path_provider: ^2.0.8
  flutter_cache_manager: ^3.3.0
  numberpicker: ^2.1.1
  url_launcher: ^6.0.18
#  webview_flutter: ^4.0.4

  dotted_border: ^2.0.0+2
  modal_bottom_sheet: ^2.0.0
  firebase_dynamic_links: ^5.0.3
  share: ^2.0.4
  firebase_analytics: ^10.0.3
  firebase_storage: ^11.0.3
  firebase_in_app_messaging: ^0.7.0+3
  shimmer: ^2.0.0
  lottie: ^1.2.1
  chewie: ^1.3.4
  device_info: ^2.0.3

  # new Version


  freezed_annotation: ^2.0.3
  encrypt: ^5.0.1
  cloud_firestore: ^4.0.3
  modal_progress_hud_nsn: ^0.3.0

  youtube_explode_dart: any
  in_app_purchase: ^3.0.4
#  connectivity_plus: ^3.0.2
  connectivity_plus: ^2.2.1
  injectable: ^1.5.3
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  permission_handler: ^10.0.0
  package_info_plus: ^1.4.2
  logging:
  provider: ^6.0.2
  rate_my_app: ^1.1.3
  another_flushbar: ^1.10.29
  cached_network_image: ^3.2.1
  scroll_to_index: ^3.0.1
  logger: ^1.1.0
  pdfx: ^1.0.1+1
  internet_file: ^1.0.0+2
  flutter_svg: any
  native_pdf_view: ^6.0.0+1
  dio: ^4.0.6
  responsive_builder: ^0.4.2
  wakelock: ^0.6.2
  get: ^4.6.5
  json_annotation: any
  flutter_local_notifications: ^12.0.3
  epub_view: ^3.0.0
  webview_flutter: ^3.0.4
  liquid_progress_indicator: ^0.4.0
  flutter_hooks: ^0.18.5+1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2











dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:

  injectable_generator: ^1.5.3
  json_serializable: any



flutter:

  # The following line ensures that the Material Icon's font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/images/
    - assets/image/
    - assets/json/
    - assets/payment/