// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5UiikQU2_-_omC-qKYcXA0X4Ta8whfuI',
    appId: '1:165257927521:web:3d145f0c2b04eafd',
    messagingSenderId: '165257927521',
    projectId: 'i-prep',
    authDomain: 'iprep-7f10a.firebaseapp.com',
    databaseURL: 'https://iprep-7f10a.firebaseio.com',
    storageBucket: 'iprep-7f10a.appspot.com',
    measurementId: 'G-SXFQPY83P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Qk3M9IpKMnOkC6ztIeMFXT69QzLugaM',
    appId: '1:165257927521:android:73b90f36640680da',
    messagingSenderId: '165257927521',
    projectId: 'i-prep',
    databaseURL: 'https://iprep-7f10a.firebaseio.com',
    storageBucket: 'iprep-7f10a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAkbi0sDlujSs0xX2Vnn6tuWrHgp_GXvg',
    appId: '1:165257927521:ios:d048f9fb44ce5c6163c320',
    messagingSenderId: '165257927521',
    projectId: 'i-prep',
    databaseURL: 'https://iprep-7f10a.firebaseio.com',
    storageBucket: 'iprep-7f10a.appspot.com',
    androidClientId:
        '165257927521-04arsif2ev80o8od30rmhdvsi25cpvnr.apps.googleusercontent.com',
    iosClientId:
        '165257927521-a0b8g7qmneqbpescfa4qhur3bof0oqsk.apps.googleusercontent.com',
    iosBundleId: 'org.idreameducation.iprepapp',
  );
}
